org:
  jobrunr:
    background-job-server:
      enabled: true
      worker-count: 4
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jobrunr
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
